
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class f extends javax.swing.JFrame {

    /**
     * Creates new form f
     */
    CardLayout c1;
    itemDB idb;
    itemDB iodb;
    String name;
    int total=0;
    int cnt;
    int indexItem ,indexOrderedItem;
    String itemName;
    int itemRate,itemQnty;
    JButton b[];
     //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    public f() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setSize(screenSize.width,screenSize.height);
        idb=new itemDB();
        iodb=new itemDB();
        System.out.println(idb);
        System.out.println(iodb);
        iodb.clearItems();
          System.out.println(iodb+"@@@@@@@@@@@@");
        cnt=idb.getItemList().size();
         b= new JButton[cnt];
         int i;
       for(i=0;i<cnt;++i)
        {
            b[i]=(JButton)jPNimg.getComponent(i);
        }
        c1=(CardLayout) this.jPNdeck.getLayout();
        this.initialize();
        Timer timer = new Timer(1000, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd");//dd/MM/yyyy
                SimpleDateFormat sdftime = new SimpleDateFormat("HH:mm:ss");//dd/MM/yyyy
                Date now = new Date();
                String strDate = sdfDate.format(now);
                String strTime = sdftime.format(now);
                jTFdate.setText("Date: "+strDate);
                jTFtime.setText("Time: "+strTime);
            }
        }
        );
        timer.start();
    }
    void initialize()
    {
        iodb.clearItems();
    }
    void processName(ActionEvent evt)
    {
        //System.out.println(iodb);
        int i;
        JButton bb=(JButton)evt.getSource();
        //System.out.println(evt.getSource());
        for(i=0;i<cnt;++i)
        {
            if(b[i]==bb)
            break;
        }
        indexItem=i;
        itemName=idb.getItem(indexItem).getName();
        indexOrderedItem=iodb.search(itemName);
     //   System.out.println(indexOrderedItem);
        if(indexOrderedItem==-1)
        {
            System.out.println("Not Repeated");
        }
        else
        {
            if(jTFqnty.getText().equals(0+""))
            {
                iodb.removeItem(i);
            }
            //int z=iodb.getItem(i).getQnty();
            int pos=jTABill.getText().indexOf(itemName);
           jTABill.setSelectionStart(pos);
            jTABill.setSelectionEnd(pos+idb.getItem(indexItem).toString().length());
            jTABill.getCaret().setSelectionVisible(true);
           // int x=iodb.getItem(i).getQnty();
             
            //System.out.println(x);
        }
        itemRate=idb.getItem(indexItem).getRate();
        this.jTFselecteditems.setText(itemName+" ("+this.itemRate+"/-)");
       // System.out.println(iodb);
    }
    void processQnty(ActionEvent evt)
    {
        String q;
       q=this.jTFqnty.getText();
       // System.out.println(q+"start");
       q=q+Integer.parseInt(evt.getActionCommand());
       this.jTFqnty.setText(q);
        //System.out.println(q+"Final");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFname = new javax.swing.JTextField();
        jBTlogo = new javax.swing.JButton();
        jTFselecteditems = new javax.swing.JTextField();
        jTFqnty = new javax.swing.JTextField();
        jBTnew = new javax.swing.JButton();
        jPN2 = new javax.swing.JPanel();
        jBTnext = new javax.swing.JButton();
        jBTprev = new javax.swing.JButton();
        jBTequals = new javax.swing.JButton();
        jPNdeck = new javax.swing.JPanel();
        jPNimg = new javax.swing.JPanel();
        jBTfavlour1 = new javax.swing.JButton();
        jBTflavour2 = new javax.swing.JButton();
        jBTflavour3 = new javax.swing.JButton();
        jBTflavour4 = new javax.swing.JButton();
        jBTflavour5 = new javax.swing.JButton();
        jBTflavour6 = new javax.swing.JButton();
        jBTflavour7 = new javax.swing.JButton();
        jBTflavour8 = new javax.swing.JButton();
        jBTflavour9 = new javax.swing.JButton();
        jPNnum = new javax.swing.JPanel();
        jBT7 = new javax.swing.JButton();
        jBT8 = new javax.swing.JButton();
        jBT9 = new javax.swing.JButton();
        jBT4 = new javax.swing.JButton();
        jBT5 = new javax.swing.JButton();
        jBT6 = new javax.swing.JButton();
        jBT1 = new javax.swing.JButton();
        jBT2 = new javax.swing.JButton();
        jBT3 = new javax.swing.JButton();
        jBT0 = new javax.swing.JButton();
        jBTc = new javax.swing.JButton();
        jPNtext = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTABill = new javax.swing.JTextArea();
        jTFdate = new javax.swing.JTextField();
        jTFtime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));
        setSize(new java.awt.Dimension(1000, 500));

        jTFname.setBackground(new java.awt.Color(255, 153, 0));
        jTFname.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTFname.setForeground(new java.awt.Color(255, 255, 0));
        jTFname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFname.setText("Bajaj IceCream Parlour");
        jTFname.setPreferredSize(new java.awt.Dimension(50, 50));
        jTFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnameActionPerformed(evt);
            }
        });

        jBTlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        jBTlogo.setIconTextGap(0);
        jBTlogo.setPreferredSize(new java.awt.Dimension(300, 233));

        jTFselecteditems.setBackground(new java.awt.Color(255, 153, 0));
        jTFselecteditems.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTFselecteditems.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFselecteditems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFselecteditemsActionPerformed(evt);
            }
        });

        jTFqnty.setBackground(new java.awt.Color(255, 153, 0));
        jTFqnty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jBTnew.setBackground(new java.awt.Color(255, 255, 255));
        jBTnew.setText("New Bill");
        jBTnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnewActionPerformed(evt);
            }
        });

        jPN2.setPreferredSize(new java.awt.Dimension(150, 400));
        jPN2.setLayout(new java.awt.GridLayout(3, 0));

        jBTnext.setBackground(new java.awt.Color(102, 255, 51));
        jBTnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/next.jpg"))); // NOI18N
        jBTnext.setIconTextGap(0);
        jBTnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTnextActionPerformed(evt);
            }
        });
        jPN2.add(jBTnext);

        jBTprev.setBackground(new java.awt.Color(255, 0, 0));
        jBTprev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/previous.jpg"))); // NOI18N
        jBTprev.setIconTextGap(0);
        jBTprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTprevActionPerformed(evt);
            }
        });
        jPN2.add(jBTprev);

        jBTequals.setBackground(new java.awt.Color(51, 51, 255));
        jBTequals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enter.jpg"))); // NOI18N
        jBTequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTequalsActionPerformed(evt);
            }
        });
        jPN2.add(jBTequals);

        jPNdeck.setPreferredSize(new java.awt.Dimension(450, 400));
        jPNdeck.setLayout(new java.awt.CardLayout());

        jPNimg.setPreferredSize(new java.awt.Dimension(445, 445));
        jPNimg.setLayout(new java.awt.GridLayout(3, 3));

        jBTfavlour1.setForeground(new java.awt.Color(255, 255, 255));
        jBTfavlour1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anjir.jpg"))); // NOI18N
        jBTfavlour1.setBorder(null);
        jBTfavlour1.setBorderPainted(false);
        jBTfavlour1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jBTfavlour1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBTfavlour1.setPreferredSize(new java.awt.Dimension(150, 100));
        jBTfavlour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTfavlour1ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTfavlour1);

        jBTflavour2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/butterscotch.jpg"))); // NOI18N
        jBTflavour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour2ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour2);

        jBTflavour3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chocolate.jpg"))); // NOI18N
        jBTflavour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour3ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour3);

        jBTflavour4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gulkand.jpg"))); // NOI18N
        jBTflavour4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour4ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour4);

        jBTflavour5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mango.jpg"))); // NOI18N
        jBTflavour5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour5ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour5);

        jBTflavour6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pineapple.jpg"))); // NOI18N
        jBTflavour6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour6ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour6);

        jBTflavour7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sitafal.jpg"))); // NOI18N
        jBTflavour7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour7ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour7);

        jBTflavour8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/strawberry.jpg"))); // NOI18N
        jBTflavour8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour8ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour8);

        jBTflavour9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vanilla.jpg"))); // NOI18N
        jBTflavour9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTflavour9ActionPerformed(evt);
            }
        });
        jPNimg.add(jBTflavour9);

        jPNdeck.add(jPNimg, "card2");

        jPNnum.setPreferredSize(new java.awt.Dimension(450, 450));
        jPNnum.setLayout(new java.awt.GridLayout(4, 3));

        jBT7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT7.setText("7");
        jBT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT7ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT7);

        jBT8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT8.setText("8");
        jBT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT8ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT8);

        jBT9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT9.setText("9");
        jBT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT9ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT9);

        jBT4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT4.setText("4");
        jBT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT4ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT4);

        jBT5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT5.setText("5");
        jBT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT5ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT5);

        jBT6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT6.setText("6");
        jBT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT6ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT6);

        jBT1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT1.setText("1");
        jBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT1ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT1);

        jBT2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT2.setText("2");
        jBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT2ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT2);

        jBT3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT3.setText("3");
        jBT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT3ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT3);

        jBT0.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBT0.setText("0");
        jBT0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT0ActionPerformed(evt);
            }
        });
        jPNnum.add(jBT0);

        jBTc.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jBTc.setText("C");
        jBTc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTcActionPerformed(evt);
            }
        });
        jPNnum.add(jBTc);

        jPNdeck.add(jPNnum, "card3");

        jPNtext.setPreferredSize(new java.awt.Dimension(1050, 151));

        javax.swing.GroupLayout jPNtextLayout = new javax.swing.GroupLayout(jPNtext);
        jPNtext.setLayout(jPNtextLayout);
        jPNtextLayout.setHorizontalGroup(
            jPNtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPNtextLayout.setVerticalGroup(
            jPNtextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBar(jScrollPane2.createVerticalScrollBar());

        jTABill.setBackground(new java.awt.Color(255, 153, 0));
        jTABill.setColumns(20);
        jTABill.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTABill.setRows(5);
        jTABill.setPreferredSize(new java.awt.Dimension(1000, 150));
        jScrollPane2.setViewportView(jTABill);

        jTFdate.setBackground(new java.awt.Color(255, 153, 0));

        jTFtime.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFselecteditems, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(jTFqnty, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jBTnew, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFtime, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jTFdate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBTlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFname, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPNdeck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPNtext, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(398, 398, 398))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBTlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFselecteditems, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFqnty, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTFdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBTnew, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFtime))))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPNtext, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPN2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPNdeck, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setBounds(0, 0, 1458, 819);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnameActionPerformed

    private void jBTnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnextActionPerformed
        // TODO add your handling code here:
        c1.next(jPNdeck);
    }//GEN-LAST:event_jBTnextActionPerformed

    private void jBTprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTprevActionPerformed
        // TODO add your handling code here:
        c1.previous(jPNdeck);
    }//GEN-LAST:event_jBTprevActionPerformed

    private void jBTflavour4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour4ActionPerformed
       processName(evt);   // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour4ActionPerformed

    private void jBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT1ActionPerformed
            processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT1ActionPerformed

    private void jBTfavlour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTfavlour1ActionPerformed
        processName(evt);   // TODO add your handling code here:
    }//GEN-LAST:event_jBTfavlour1ActionPerformed

    private void jBTflavour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour2ActionPerformed
         processName(evt); // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour2ActionPerformed

    private void jBTflavour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour3ActionPerformed
         processName(evt); // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour3ActionPerformed

    private void jBTflavour5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour5ActionPerformed
         processName(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour5ActionPerformed

    private void jBTflavour6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour6ActionPerformed
         processName(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour6ActionPerformed

    private void jBTflavour7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour7ActionPerformed
         processName(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour7ActionPerformed

    private void jBTflavour8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour8ActionPerformed
         processName(evt);         // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour8ActionPerformed

    private void jBTflavour9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTflavour9ActionPerformed
         processName(evt);   // TODO add your handling code here:
    }//GEN-LAST:event_jBTflavour9ActionPerformed

    private void jBT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT7ActionPerformed
        processQnty(evt);// TODO add your handling code here:
    }//GEN-LAST:event_jBT7ActionPerformed

    private void jBT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT8ActionPerformed
        processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT8ActionPerformed

    private void jBT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT9ActionPerformed
        processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT9ActionPerformed

    private void jBT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT4ActionPerformed
        processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT4ActionPerformed

    private void jBT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT5ActionPerformed
        processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT5ActionPerformed

    private void jBT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT6ActionPerformed
        processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT6ActionPerformed

    private void jBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT2ActionPerformed
        processQnty(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jBT2ActionPerformed

    private void jBT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT3ActionPerformed
        processQnty(evt);// TODO add your handling code here:
    }//GEN-LAST:event_jBT3ActionPerformed

    private void jBT0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT0ActionPerformed
         String s=jTFselecteditems.getText();
        int i=s.indexOf(" ");
        s=s.substring(0,i);
        int pos=iodb.search(s);
        if(evt.getActionCommand().equals(0+"") && pos==-1){
            Toolkit.getDefaultToolkit().beep();
        }else{
            total=total-iodb.getItem(pos).getQnty()*iodb.getItem(pos).getRate();
            iodb.removeItem(pos);
           // c1.previous(jPNdeck);
            jTABill.setText(iodb+"\nTotal->"+total);// TODO add your handling code here:
    }//GEN-LAST:event_jBT0ActionPerformed
    }
    private void jBTcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTcActionPerformed
               String s;
        s=this.jTFqnty.getText();
        s=s.substring(0, s.length()-1);
        this.jTFqnty.setText(s);  // TODO add your handling code here:
    }//GEN-LAST:event_jBTcActionPerformed

    private void jBTequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTequalsActionPerformed
        int i;
        try {
           itemQnty=Integer.parseInt(this.jTFqnty.getText());
        } catch (Exception e) {
            jTABill.setText("No fruit selected...");
            return;
        }    
        // Add this item in the list
       Item item=null;
        if(itemQnty!=0 && iodb.search(itemName)==-1){
        item=new Item(itemName,itemRate,itemQnty ) ;
       this.iodb.addItem(item);
       total=total+item.getRate()*Integer.parseInt(this.jTFqnty.getText());
        } 
        else
        {
        int repeat=iodb.search(itemName);
         int x=iodb.getItem(repeat).getQnty();
            System.out.println(x);
        int z=Integer.parseInt(jTFqnty.getText());
            System.out.println(z);
        iodb.getItem(repeat).setQnty(z);
       total=total+iodb.getItem(repeat).getRate()*(z-x);
//         total=total+item.getRate()*Integer.parseInt(this.jTFqnty.getText());
        }
        jTABill.setText(""+iodb+"\n"+"Total->"+total);
       this.jTFqnty.setText("");
        this.jTFselecteditems.setText("");
        c1.previous(jPNdeck);
            // TODO add your handling code here:
        System.out.println(iodb);
    }//GEN-LAST:event_jBTequalsActionPerformed

    private void jBTnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTnewActionPerformed
        this.jTABill.setText("");
        iodb=new itemDB();
        iodb.clearItems();
        total=0;// TODO add your handling code here:
    }//GEN-LAST:event_jBTnewActionPerformed

    private void jTFselecteditemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFselecteditemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFselecteditemsActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT0;
    private javax.swing.JButton jBT1;
    private javax.swing.JButton jBT2;
    private javax.swing.JButton jBT3;
    private javax.swing.JButton jBT4;
    private javax.swing.JButton jBT5;
    private javax.swing.JButton jBT6;
    private javax.swing.JButton jBT7;
    private javax.swing.JButton jBT8;
    private javax.swing.JButton jBT9;
    private javax.swing.JButton jBTc;
    private javax.swing.JButton jBTequals;
    private javax.swing.JButton jBTfavlour1;
    private javax.swing.JButton jBTflavour2;
    private javax.swing.JButton jBTflavour3;
    private javax.swing.JButton jBTflavour4;
    private javax.swing.JButton jBTflavour5;
    private javax.swing.JButton jBTflavour6;
    private javax.swing.JButton jBTflavour7;
    private javax.swing.JButton jBTflavour8;
    private javax.swing.JButton jBTflavour9;
    private javax.swing.JButton jBTlogo;
    private javax.swing.JButton jBTnew;
    private javax.swing.JButton jBTnext;
    private javax.swing.JButton jBTprev;
    private javax.swing.JPanel jPN2;
    private javax.swing.JPanel jPNdeck;
    private javax.swing.JPanel jPNimg;
    private javax.swing.JPanel jPNnum;
    private javax.swing.JPanel jPNtext;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTABill;
    private javax.swing.JTextField jTFdate;
    private javax.swing.JTextField jTFname;
    private javax.swing.JTextField jTFqnty;
    private javax.swing.JTextField jTFselecteditems;
    private javax.swing.JTextField jTFtime;
    // End of variables declaration//GEN-END:variables
}
